{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-beans",
    "version": "6.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-6.0.12.jar",
          "url": "spring-beans-6.0.12.jar",
          "size": 857021,
          "sha512": "395e3c23bb14348afae3597b951a6349dc420e2f28b5c71f02bbd930cb77e008bf42e65a1d84622db8bd3d7c08fd4160e78d10b4e733b2dd2e8268945554e46b",
          "sha256": "75b5dfed8723703797e6e835154aca6e771b683da0307898ab9816037e936138",
          "sha1": "dfa53afbf1ab65f36c60333443ed1109ed331504",
          "md5": "68e2ce18001437a73142f93cec32f9dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-6.0.12.jar",
          "url": "spring-beans-6.0.12.jar",
          "size": 857021,
          "sha512": "395e3c23bb14348afae3597b951a6349dc420e2f28b5c71f02bbd930cb77e008bf42e65a1d84622db8bd3d7c08fd4160e78d10b4e733b2dd2e8268945554e46b",
          "sha256": "75b5dfed8723703797e6e835154aca6e771b683da0307898ab9816037e936138",
          "sha1": "dfa53afbf1ab65f36c60333443ed1109ed331504",
          "md5": "68e2ce18001437a73142f93cec32f9dd"
        }
      ]
    }
  ]
}
