{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aop",
    "version": "6.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.0.12.jar",
          "url": "spring-aop-6.0.12.jar",
          "size": 404411,
          "sha512": "1f173432345c43b4e99a018206a3f3d4eb9e851d2fbcd7e660cabb919b5f0f929ab8cf84965ccbb8ed8e1e691274523366e82f61c670de95ad3f8fb02540f92a",
          "sha256": "f8c735ac2c6d3fe7759ef05b0088115b01f4c43b1076de8070612f0b7dd6f5e4",
          "sha1": "ba7ecdbdc2abaf172d49692b8110f65ecd2d250c",
          "md5": "8627688dd9370927ba35daf78a56c387"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.0.12.jar",
          "url": "spring-aop-6.0.12.jar",
          "size": 404411,
          "sha512": "1f173432345c43b4e99a018206a3f3d4eb9e851d2fbcd7e660cabb919b5f0f929ab8cf84965ccbb8ed8e1e691274523366e82f61c670de95ad3f8fb02540f92a",
          "sha256": "f8c735ac2c6d3fe7759ef05b0088115b01f4c43b1076de8070612f0b7dd6f5e4",
          "sha1": "ba7ecdbdc2abaf172d49692b8110f65ecd2d250c",
          "md5": "8627688dd9370927ba35daf78a56c387"
        }
      ]
    }
  ]
}
