{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-json",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.1.3.jar",
          "url": "spring-boot-starter-json-3.1.3.jar",
          "size": 4747,
          "sha512": "8cfbf2babe639ec97c028aa1fe1e4e240d15e75fae196baa96fb6dbfe7cb8a0afecc925bb9669d2c3a8d31e994ccb56bfa90551c657fa0e477af485c8446705f",
          "sha256": "28b7c713a52b66607214181ac0aab1c482fa80d092b7ba2898ce6351f2361593",
          "sha1": "853a7b3152846d685e38c34ad8e14f221228c846",
          "md5": "3b6ca15e598dad14a4c7259e03d01620"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.1.3.jar",
          "url": "spring-boot-starter-json-3.1.3.jar",
          "size": 4747,
          "sha512": "8cfbf2babe639ec97c028aa1fe1e4e240d15e75fae196baa96fb6dbfe7cb8a0afecc925bb9669d2c3a8d31e994ccb56bfa90551c657fa0e477af485c8446705f",
          "sha256": "28b7c713a52b66607214181ac0aab1c482fa80d092b7ba2898ce6351f2361593",
          "sha1": "853a7b3152846d685e38c34ad8e14f221228c846",
          "md5": "3b6ca15e598dad14a4c7259e03d01620"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.1.3.jar",
          "url": "spring-boot-starter-json-3.1.3.jar",
          "size": 4747,
          "sha512": "8cfbf2babe639ec97c028aa1fe1e4e240d15e75fae196baa96fb6dbfe7cb8a0afecc925bb9669d2c3a8d31e994ccb56bfa90551c657fa0e477af485c8446705f",
          "sha256": "28b7c713a52b66607214181ac0aab1c482fa80d092b7ba2898ce6351f2361593",
          "sha1": "853a7b3152846d685e38c34ad8e14f221228c846",
          "md5": "3b6ca15e598dad14a4c7259e03d01620"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.1.3.jar",
          "url": "spring-boot-starter-json-3.1.3.jar",
          "size": 4747,
          "sha512": "8cfbf2babe639ec97c028aa1fe1e4e240d15e75fae196baa96fb6dbfe7cb8a0afecc925bb9669d2c3a8d31e994ccb56bfa90551c657fa0e477af485c8446705f",
          "sha256": "28b7c713a52b66607214181ac0aab1c482fa80d092b7ba2898ce6351f2361593",
          "sha1": "853a7b3152846d685e38c34ad8e14f221228c846",
          "md5": "3b6ca15e598dad14a4c7259e03d01620"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.1.3-javadoc.jar",
          "url": "spring-boot-starter-json-3.1.3-javadoc.jar",
          "size": 4742,
          "sha512": "b1a1b705fd322561d4c674830f27b50124e08a69c84b2a6646e6c1cdaab5de5753365e44bd29359f9059762369b9c5067859172c559d1df09c6d65cfaf59cf95",
          "sha256": "2ce52c86582a7c72dfb0209a4ec1ba8865290c307aaffde5c3645d3b6e55fa80",
          "sha1": "183b5dd3cb9ac739c623f30dee5cf4e2e0779551",
          "md5": "70d7e35fed0b2ec262fca1e2d9da24bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.1.3-sources.jar",
          "url": "spring-boot-starter-json-3.1.3-sources.jar",
          "size": 4740,
          "sha512": "0b3dec08bfc67f7a262c3114c68c8b7624e5981e8210f4443084a37255590b34a3b62cda723718c98698a564c3a9e91f9c1f623eabf7e605986974868ae13784",
          "sha256": "0034d1117203c9c61b76df5e20464e3ab8215dbb3f9dda8f3344218bb8078c26",
          "sha1": "371604317005da59dfb8e4abd3276f28cb1e219d",
          "md5": "f706878768f8c82a86c765ed0a0b6f97"
        }
      ]
    }
  ]
}
