{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.0.11.jar",
          "url": "spring-webmvc-6.0.11.jar",
          "size": 1010650,
          "sha512": "95a31a5beecb42d1f4492a9388635734aa9c9e588c6d113b8fdddaffe3866b49c59cf867181dbe4787faf5af0d46eb792bcacd5b71614fb964b84653ee0afd1e",
          "sha256": "eed60debba0fe5f045c0290b326d52fc62e6cd1bb4a69dc030de55d23a6809cd",
          "sha1": "892b4a63b5d930c2c43058c6db0c2c65401fb078",
          "md5": "ccd2de5f696e9c03d367c19a67c9f4b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.0.11.jar",
          "url": "spring-webmvc-6.0.11.jar",
          "size": 1010650,
          "sha512": "95a31a5beecb42d1f4492a9388635734aa9c9e588c6d113b8fdddaffe3866b49c59cf867181dbe4787faf5af0d46eb792bcacd5b71614fb964b84653ee0afd1e",
          "sha256": "eed60debba0fe5f045c0290b326d52fc62e6cd1bb4a69dc030de55d23a6809cd",
          "sha1": "892b4a63b5d930c2c43058c6db0c2c65401fb078",
          "md5": "ccd2de5f696e9c03d367c19a67c9f4b3"
        }
      ]
    }
  ]
}
