{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.12"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.12"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.12"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.1.3.jar",
          "url": "spring-boot-starter-tomcat-3.1.3.jar",
          "size": 4792,
          "sha512": "e4094e02e9f08d516c960dc0b20f177e4ec558461959d57ae11989f223a696b9f550ba07c7a2eb9f91e790a1c41f5167d1b3e0261772052fedbcd8cc7b6c83f3",
          "sha256": "0e70e8476519e6c3d44e710b2b92a0919f8afa8123da5717807525395139d486",
          "sha1": "af588c29407cd056296be081c281b3e196c4860a",
          "md5": "dc6384c796124fbd54544738cdf44526"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.12"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.12"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.12"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.1.3.jar",
          "url": "spring-boot-starter-tomcat-3.1.3.jar",
          "size": 4792,
          "sha512": "e4094e02e9f08d516c960dc0b20f177e4ec558461959d57ae11989f223a696b9f550ba07c7a2eb9f91e790a1c41f5167d1b3e0261772052fedbcd8cc7b6c83f3",
          "sha256": "0e70e8476519e6c3d44e710b2b92a0919f8afa8123da5717807525395139d486",
          "sha1": "af588c29407cd056296be081c281b3e196c4860a",
          "md5": "dc6384c796124fbd54544738cdf44526"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.1.3.jar",
          "url": "spring-boot-starter-tomcat-3.1.3.jar",
          "size": 4792,
          "sha512": "e4094e02e9f08d516c960dc0b20f177e4ec558461959d57ae11989f223a696b9f550ba07c7a2eb9f91e790a1c41f5167d1b3e0261772052fedbcd8cc7b6c83f3",
          "sha256": "0e70e8476519e6c3d44e710b2b92a0919f8afa8123da5717807525395139d486",
          "sha1": "af588c29407cd056296be081c281b3e196c4860a",
          "md5": "dc6384c796124fbd54544738cdf44526"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.1.3.jar",
          "url": "spring-boot-starter-tomcat-3.1.3.jar",
          "size": 4792,
          "sha512": "e4094e02e9f08d516c960dc0b20f177e4ec558461959d57ae11989f223a696b9f550ba07c7a2eb9f91e790a1c41f5167d1b3e0261772052fedbcd8cc7b6c83f3",
          "sha256": "0e70e8476519e6c3d44e710b2b92a0919f8afa8123da5717807525395139d486",
          "sha1": "af588c29407cd056296be081c281b3e196c4860a",
          "md5": "dc6384c796124fbd54544738cdf44526"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.1.3-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.1.3-javadoc.jar",
          "size": 4742,
          "sha512": "1cfbb6de3e7adf27de8c281fdf03a32a80eff07a118992823be991d40dc89bdd7edc658a7838c8bff9b733325b849506c4b8179bf7718feaae00aa0bc19db5b3",
          "sha256": "5238a7bbd8ba3251572e72e5917266c72de7d2c50718ab1855cab175493fec4d",
          "sha1": "72398f4767bfa3c53741cf29418dba78dd9da82b",
          "md5": "43ca44fcbdef8a76bb15fc7fd92205b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.1.3-sources.jar",
          "url": "spring-boot-starter-tomcat-3.1.3-sources.jar",
          "size": 4741,
          "sha512": "83f102aef1d7f818b5d0727de4ccebd866f55e75eae9621b9fa7f091dd3ad501d5a0d127b1b44ddb5df6686dfdf45c3ae36100b8778c495ce07069dccc7f367d",
          "sha256": "470db4ebf4afa0c199b8a3718d239104049b26a6d001ff9ebd93a37532e0e534",
          "sha1": "4bfff5c267c7b464f00efe7361f8cfc18fae04ed",
          "md5": "6565b3b3ed0cd283a3f15d24ce7288f1"
        }
      ]
    }
  ]
}
