{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.1.3.jar",
          "url": "spring-boot-starter-3.1.3.jar",
          "size": 4767,
          "sha512": "f7e8e6672738bea891b0a0d8370321cd68b407004cbda5454b3e10187bb517f6680ab3cc0c53c81e080f9900f7173972d9f1b575d4c40c60bb2488ecaac4debc",
          "sha256": "bd50ae21736187ab1119f6bbd99f5a5bbdae9fdc0e7cedd7b2279de33b17aa71",
          "sha1": "c59f038f005cf8fb3338b7b9e50e9a65bac1ebca",
          "md5": "7ac593509bb419f20335b412de30f810"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.11"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.1.3.jar",
          "url": "spring-boot-starter-3.1.3.jar",
          "size": 4767,
          "sha512": "f7e8e6672738bea891b0a0d8370321cd68b407004cbda5454b3e10187bb517f6680ab3cc0c53c81e080f9900f7173972d9f1b575d4c40c60bb2488ecaac4debc",
          "sha256": "bd50ae21736187ab1119f6bbd99f5a5bbdae9fdc0e7cedd7b2279de33b17aa71",
          "sha1": "c59f038f005cf8fb3338b7b9e50e9a65bac1ebca",
          "md5": "7ac593509bb419f20335b412de30f810"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.1.3.jar",
          "url": "spring-boot-starter-3.1.3.jar",
          "size": 4767,
          "sha512": "f7e8e6672738bea891b0a0d8370321cd68b407004cbda5454b3e10187bb517f6680ab3cc0c53c81e080f9900f7173972d9f1b575d4c40c60bb2488ecaac4debc",
          "sha256": "bd50ae21736187ab1119f6bbd99f5a5bbdae9fdc0e7cedd7b2279de33b17aa71",
          "sha1": "c59f038f005cf8fb3338b7b9e50e9a65bac1ebca",
          "md5": "7ac593509bb419f20335b412de30f810"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.1.3.jar",
          "url": "spring-boot-starter-3.1.3.jar",
          "size": 4767,
          "sha512": "f7e8e6672738bea891b0a0d8370321cd68b407004cbda5454b3e10187bb517f6680ab3cc0c53c81e080f9900f7173972d9f1b575d4c40c60bb2488ecaac4debc",
          "sha256": "bd50ae21736187ab1119f6bbd99f5a5bbdae9fdc0e7cedd7b2279de33b17aa71",
          "sha1": "c59f038f005cf8fb3338b7b9e50e9a65bac1ebca",
          "md5": "7ac593509bb419f20335b412de30f810"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.1.3-javadoc.jar",
          "url": "spring-boot-starter-3.1.3-javadoc.jar",
          "size": 4734,
          "sha512": "5355c1b69bdfea2d6c8ae87b22a67d0b24df1e865a20e17c0f23e9e7130db7bb892ec33aec5a26c0cb1a35ad1bac430cabc7ecb11f1a90715aadf1ebb1434721",
          "sha256": "323d2abeed4c87163aaa9055ea55e7ccd14d36d52c5350c173555dd56968ea3a",
          "sha1": "9015febff6b9da524af1c699f04165243d3612d4",
          "md5": "263a323b3473c0d11aa1e1eb683bebad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.1.3-sources.jar",
          "url": "spring-boot-starter-3.1.3-sources.jar",
          "size": 4733,
          "sha512": "ffebf7f0d5f2141c1ec764907bbf85cdd2ec800c1e1da77dc81b814a33af973f3dfade19fc35bbc3766fedfa5ece677f48d864484a18005569f402779548930c",
          "sha256": "4255f0e6727c58d2b3ead76dc318817552f549f29e727ddfa28a3a6ad4a78eea",
          "sha1": "2c34531c87504f0deb7a210f0941140c1c85e33e",
          "md5": "0d6dc0d94e107e64831eb8bc6f68d83d"
        }
      ]
    }
  ]
}
