{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "3.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.1.4.jar",
          "url": "spring-boot-3.1.4.jar",
          "size": 1541526,
          "sha512": "8f3be369bd3af2068e91912adf3786ae5457af3eba95e045a12c85656aa2d0f17023404cf38fa9c8556176bceb8b459c9bc579ad377b322367ca867218085838",
          "sha256": "4ab47cf74fbcc4dcc82a8b82122307ef252081514263d8058d2752177b0ec0bf",
          "sha1": "7a0a6349e28227a93f2b4efde897e87b3343bf3a",
          "md5": "8e4565762f1e7113cc7ee6d0e201435b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.1.4.jar",
          "url": "spring-boot-3.1.4.jar",
          "size": 1541526,
          "sha512": "8f3be369bd3af2068e91912adf3786ae5457af3eba95e045a12c85656aa2d0f17023404cf38fa9c8556176bceb8b459c9bc579ad377b322367ca867218085838",
          "sha256": "4ab47cf74fbcc4dcc82a8b82122307ef252081514263d8058d2752177b0ec0bf",
          "sha1": "7a0a6349e28227a93f2b4efde897e87b3343bf3a",
          "md5": "8e4565762f1e7113cc7ee6d0e201435b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.1.4-javadoc.jar",
          "url": "spring-boot-3.1.4-javadoc.jar",
          "size": 2245523,
          "sha512": "0e5572acc3160715b700e301c95de94cad3d74564f74197b0b09b52a681f608925f706ff354f00ee4c90a9249d6bff6561ff4f25baa24190a28361e6b89c4b1a",
          "sha256": "074b260890ee3d10f5d482f219404e8fd2b7f2992eee0a6e37c7118335beda8b",
          "sha1": "8b239d91e8a952642c529637d05170fa497cef82",
          "md5": "1903f3eeb48598036c28e8f763b4eba7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.1.4-sources.jar",
          "url": "spring-boot-3.1.4-sources.jar",
          "size": 1067638,
          "sha512": "e44102e78ebfbe2ecd4aa251ea5787a11a1cd85b29f0f7f23837b106fd2494a0ada67175c0a005a0098761b059e32e1c3eab1de886d4a3e15ca90b253dd96ba9",
          "sha256": "ecf549b1363ae6712119f36d3b67f1c399163837df698eca2f96da31057f751d",
          "sha1": "b6032fdb85edfff75e8455e8629887a1a8674d17",
          "md5": "ae7980c89c5a8327869ed064e74ea9f9"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-3.1.4.jar",
          "url": "spring-boot-3.1.4.jar",
          "size": 1541526,
          "sha512": "8f3be369bd3af2068e91912adf3786ae5457af3eba95e045a12c85656aa2d0f17023404cf38fa9c8556176bceb8b459c9bc579ad377b322367ca867218085838",
          "sha256": "4ab47cf74fbcc4dcc82a8b82122307ef252081514263d8058d2752177b0ec0bf",
          "sha1": "7a0a6349e28227a93f2b4efde897e87b3343bf3a",
          "md5": "8e4565762f1e7113cc7ee6d0e201435b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "3.1.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.1.4.jar",
          "url": "spring-boot-3.1.4.jar",
          "size": 1541526,
          "sha512": "8f3be369bd3af2068e91912adf3786ae5457af3eba95e045a12c85656aa2d0f17023404cf38fa9c8556176bceb8b459c9bc579ad377b322367ca867218085838",
          "sha256": "4ab47cf74fbcc4dcc82a8b82122307ef252081514263d8058d2752177b0ec0bf",
          "sha1": "7a0a6349e28227a93f2b4efde897e87b3343bf3a",
          "md5": "8e4565762f1e7113cc7ee6d0e201435b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "3.1.4"
        }
      ]
    }
  ]
}
