{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context",
    "version": "6.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-6.0.12.jar",
          "url": "spring-context-6.0.12.jar",
          "size": 1185769,
          "sha512": "4717bd8436ba726db955911a9f5f028595f6990442c9608032550d56b986556dee3cac7d7a619a06dafabb1684efe246762d99e9cf5fdabdea52c0dac2e829cd",
          "sha256": "9f19eec7b8f943eba0c0a39a01549a28854f667820935bc9d120a9d53ffb8efc",
          "sha1": "f1964518e07796b2fdc1b9be2108485ffe1b4566",
          "md5": "fc55461af3ae9cf2e62c1f4834213b30"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-6.0.12.jar",
          "url": "spring-context-6.0.12.jar",
          "size": 1185769,
          "sha512": "4717bd8436ba726db955911a9f5f028595f6990442c9608032550d56b986556dee3cac7d7a619a06dafabb1684efe246762d99e9cf5fdabdea52c0dac2e829cd",
          "sha256": "9f19eec7b8f943eba0c0a39a01549a28854f667820935bc9d120a9d53ffb8efc",
          "sha1": "f1964518e07796b2fdc1b9be2108485ffe1b4566",
          "md5": "fc55461af3ae9cf2e62c1f4834213b30"
        }
      ]
    }
  ]
}
