{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test-autoconfigure",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.1.3.jar",
          "url": "spring-boot-test-autoconfigure-3.1.3.jar",
          "size": 223089,
          "sha512": "a3a21f4ce62b6861202fd1aa12ee6149e7ca9c08604264b71e3210dde8d09d29e8d3257417f4a972efbc56da7709c8fadffb60a33ee398ee5bb88b76b721793f",
          "sha256": "b781443b495a4312a64308eb5489029175280b5cb12ab0dd19a424191a78ef7e",
          "sha1": "1642297bd56c29004b06a1b3441ba03939840657",
          "md5": "ec067a4dab926a1edac949e30cea78a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.1.3.jar",
          "url": "spring-boot-test-autoconfigure-3.1.3.jar",
          "size": 223089,
          "sha512": "a3a21f4ce62b6861202fd1aa12ee6149e7ca9c08604264b71e3210dde8d09d29e8d3257417f4a972efbc56da7709c8fadffb60a33ee398ee5bb88b76b721793f",
          "sha256": "b781443b495a4312a64308eb5489029175280b5cb12ab0dd19a424191a78ef7e",
          "sha1": "1642297bd56c29004b06a1b3441ba03939840657",
          "md5": "ec067a4dab926a1edac949e30cea78a9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.1.3-javadoc.jar",
          "url": "spring-boot-test-autoconfigure-3.1.3-javadoc.jar",
          "size": 501861,
          "sha512": "d552640147115f178f0ae4fa26a31d58c7baa46b5827945f90c10f8e39fd7fc0ce717dcda5b0a0d8c836cdb699f3ad14dcc1480dc9fbd829592bf084602961dd",
          "sha256": "8dd0dd41ff029f97005363aa5332c2006d850bfe8ea244003f70a0f5d30f9c77",
          "sha1": "fc361e1ec4659664726558604a95b4344a6acdf3",
          "md5": "a88464faa825f8340a5dc5720efa593d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.1.3-sources.jar",
          "url": "spring-boot-test-autoconfigure-3.1.3-sources.jar",
          "size": 224034,
          "sha512": "c51fe4c5389dacd89cb3f19c9d635c539609ac829418c35b094d91b8d146d9ecca03586a7d16f503ad0494d7904746118346038bad37f8cbc9ddad0d096713be",
          "sha256": "ef83e91794bcbd2e1bbf6bc910110bf1c460b7cfaca6f55e212c38fa270dc790",
          "sha1": "8c82feb03bd603b68aa630cd22a17d10ec32f461",
          "md5": "070956ba2d7684dd219ffd9a42f144b2"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.1.3.jar",
          "url": "spring-boot-test-autoconfigure-3.1.3.jar",
          "size": 223089,
          "sha512": "a3a21f4ce62b6861202fd1aa12ee6149e7ca9c08604264b71e3210dde8d09d29e8d3257417f4a972efbc56da7709c8fadffb60a33ee398ee5bb88b76b721793f",
          "sha256": "b781443b495a4312a64308eb5489029175280b5cb12ab0dd19a424191a78ef7e",
          "sha1": "1642297bd56c29004b06a1b3441ba03939840657",
          "md5": "ec067a4dab926a1edac949e30cea78a9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-autoconfigure-3.1.3.jar",
          "url": "spring-boot-test-autoconfigure-3.1.3.jar",
          "size": 223089,
          "sha512": "a3a21f4ce62b6861202fd1aa12ee6149e7ca9c08604264b71e3210dde8d09d29e8d3257417f4a972efbc56da7709c8fadffb60a33ee398ee5bb88b76b721793f",
          "sha256": "b781443b495a4312a64308eb5489029175280b5cb12ab0dd19a424191a78ef7e",
          "sha1": "1642297bd56c29004b06a1b3441ba03939840657",
          "md5": "ec067a4dab926a1edac949e30cea78a9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-autoconfigure-maven-optional",
          "version": "3.1.3"
        }
      ]
    }
  ]
}
