{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "3.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.4.11"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.9.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.9.1"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.1.4.jar",
          "url": "spring-boot-starter-test-3.1.4.jar",
          "size": 4791,
          "sha512": "717a2ef11a8311c9311741b32d3cd60b976f26ccd98895f0a767dc4bc01f7f77281f8fae3f0fb37835d54de618854719be5b6cd5a38c1d498ab7dc6fa5ef7320",
          "sha256": "67445f571832722eba97550923cd0d4acff57fe8e844d62c13cf2c3c74526c28",
          "sha1": "1990ee664a265366b09ac723002f72697ebd0925",
          "md5": "1c03a245430c0da9ab1b7a76976048c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.4.11"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.9.3"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.9.1"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.1.4.jar",
          "url": "spring-boot-starter-test-3.1.4.jar",
          "size": 4791,
          "sha512": "717a2ef11a8311c9311741b32d3cd60b976f26ccd98895f0a767dc4bc01f7f77281f8fae3f0fb37835d54de618854719be5b6cd5a38c1d498ab7dc6fa5ef7320",
          "sha256": "67445f571832722eba97550923cd0d4acff57fe8e844d62c13cf2c3c74526c28",
          "sha1": "1990ee664a265366b09ac723002f72697ebd0925",
          "md5": "1c03a245430c0da9ab1b7a76976048c1"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.1.4.jar",
          "url": "spring-boot-starter-test-3.1.4.jar",
          "size": 4791,
          "sha512": "717a2ef11a8311c9311741b32d3cd60b976f26ccd98895f0a767dc4bc01f7f77281f8fae3f0fb37835d54de618854719be5b6cd5a38c1d498ab7dc6fa5ef7320",
          "sha256": "67445f571832722eba97550923cd0d4acff57fe8e844d62c13cf2c3c74526c28",
          "sha1": "1990ee664a265366b09ac723002f72697ebd0925",
          "md5": "1c03a245430c0da9ab1b7a76976048c1"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-test-maven-optional",
          "version": "3.1.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.1.4.jar",
          "url": "spring-boot-starter-test-3.1.4.jar",
          "size": 4791,
          "sha512": "717a2ef11a8311c9311741b32d3cd60b976f26ccd98895f0a767dc4bc01f7f77281f8fae3f0fb37835d54de618854719be5b6cd5a38c1d498ab7dc6fa5ef7320",
          "sha256": "67445f571832722eba97550923cd0d4acff57fe8e844d62c13cf2c3c74526c28",
          "sha1": "1990ee664a265366b09ac723002f72697ebd0925",
          "md5": "1c03a245430c0da9ab1b7a76976048c1"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-test-maven-optional",
          "version": "3.1.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.1.4-javadoc.jar",
          "url": "spring-boot-starter-test-3.1.4-javadoc.jar",
          "size": 4741,
          "sha512": "46435935b9f50f6e3cdf10e3aa29bdb429c55bee864c15913c1c6aed46ed7fb5843dbf2e7a394a6e07474343687f53d6fabbf1ab4affeeac464a4ad32b0b2059",
          "sha256": "d34e89b83da1f98875dd0b757169ef1a0c31728503cf0c109defe9a95ef8b427",
          "sha1": "c840cd38ff6bd5df467c9add64c82a6407c42dc9",
          "md5": "13eeb5544445c6e4e1987b33d77fad76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.1.4-sources.jar",
          "url": "spring-boot-starter-test-3.1.4-sources.jar",
          "size": 4740,
          "sha512": "7a2df2da74ba88b40e57c688c13aadf8564a884e5f41080ca8c171ce381dd8703be059de51f36e34035341deae408a982930d53f6ccbf2c582a7834f921b35d9",
          "sha256": "d15d9534393feaa4075fbdc11d3dbc933809fdee6a46428550ab9939d92e8f54",
          "sha1": "4360634255786e1623c22981b75222197ea86e09",
          "md5": "80157f55446da7d54a3e028de92bf840"
        }
      ]
    }
  ]
}
