{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-thymeleaf",
    "version": "3.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf-spring6",
          "version": {
            "requires": "3.1.2.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.1.3.jar",
          "url": "spring-boot-starter-thymeleaf-3.1.3.jar",
          "size": 4769,
          "sha512": "013a1b9d878130051abaea6a9599ea7e9c5ef79539be51c50086590687fbfa44e3caec9714ce5c440bfba912be986749ed0838b20bad2663ca95fa673dbc3a79",
          "sha256": "fef24fa8d0e3ebc897731c2d4e7fe27729a7e5061e78550c9bfe5e4e33a799af",
          "sha1": "234ffde0db9f68f387ce99928053c9be103be789",
          "md5": "b34ddec9f5ac120c940d02d28fc6fb7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf-spring6",
          "version": {
            "requires": "3.1.2.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.1.3.jar",
          "url": "spring-boot-starter-thymeleaf-3.1.3.jar",
          "size": 4769,
          "sha512": "013a1b9d878130051abaea6a9599ea7e9c5ef79539be51c50086590687fbfa44e3caec9714ce5c440bfba912be986749ed0838b20bad2663ca95fa673dbc3a79",
          "sha256": "fef24fa8d0e3ebc897731c2d4e7fe27729a7e5061e78550c9bfe5e4e33a799af",
          "sha1": "234ffde0db9f68f387ce99928053c9be103be789",
          "md5": "b34ddec9f5ac120c940d02d28fc6fb7f"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.1.3.jar",
          "url": "spring-boot-starter-thymeleaf-3.1.3.jar",
          "size": 4769,
          "sha512": "013a1b9d878130051abaea6a9599ea7e9c5ef79539be51c50086590687fbfa44e3caec9714ce5c440bfba912be986749ed0838b20bad2663ca95fa673dbc3a79",
          "sha256": "fef24fa8d0e3ebc897731c2d4e7fe27729a7e5061e78550c9bfe5e4e33a799af",
          "sha1": "234ffde0db9f68f387ce99928053c9be103be789",
          "md5": "b34ddec9f5ac120c940d02d28fc6fb7f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-thymeleaf-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.1.3.jar",
          "url": "spring-boot-starter-thymeleaf-3.1.3.jar",
          "size": 4769,
          "sha512": "013a1b9d878130051abaea6a9599ea7e9c5ef79539be51c50086590687fbfa44e3caec9714ce5c440bfba912be986749ed0838b20bad2663ca95fa673dbc3a79",
          "sha256": "fef24fa8d0e3ebc897731c2d4e7fe27729a7e5061e78550c9bfe5e4e33a799af",
          "sha1": "234ffde0db9f68f387ce99928053c9be103be789",
          "md5": "b34ddec9f5ac120c940d02d28fc6fb7f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-thymeleaf-maven-optional",
          "version": "3.1.3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.1.3-javadoc.jar",
          "url": "spring-boot-starter-thymeleaf-3.1.3-javadoc.jar",
          "size": 4746,
          "sha512": "b92c3fd8b78aed05923ecd588089c1511fb7381af0c6b9dd8e294a292c0484b1438a6ddf876dba9627f23f3fb0c55f07b8803322d358ccb5df966471cd7823b4",
          "sha256": "63fafdd31009e61310c537f3965c3aa5d9b026a95e6b30f3d4b90c35e8477233",
          "sha1": "dd1b5f91e3d528c484d3a56b5ec353715bbb6d4e",
          "md5": "1c8f152e16fbabb220f049b6d28c9b56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.1.3-sources.jar",
          "url": "spring-boot-starter-thymeleaf-3.1.3-sources.jar",
          "size": 4744,
          "sha512": "4a3ef8b4e6684ebc3e590df6d2c8d8e11164c973d9b43b28e6b9fb8d67ef4727a92dfe6a8802d279c6c3a6d31d94ea9f668de12e1d85a89c7859d3b925e76534",
          "sha256": "04aa641e561101038f993c649bc61bd663cf44623bdf7f9caf0312871be548dc",
          "sha1": "83ad4c70e15ee581b26139decf38e5c83223b904",
          "md5": "1b902aa6dfe2c1e4c1f95c9fc030ffde"
        }
      ]
    }
  ]
}
