{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-parameter-names",
    "version": "2.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.15.2.jar",
          "url": "jackson-module-parameter-names-2.15.2.jar",
          "size": 9475,
          "sha512": "89b066c1d10ef9703d943c9f2d388478b59d089cd0134d06523b0be194fae8f557add7dbb4f7e16296f64b27f3b6d2f2fa498087bfb4d8bb45dace433d35930e",
          "sha256": "ebf445ed0897a0e061ee91a43e9e1599a8aaf2f4b79786001bdf4edd256289f4",
          "sha1": "c28f41ceca6cb390eaa492db6d01ec3eb3453af1",
          "md5": "9293dcded6363780aaf339632ebba6b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.15.2.jar",
          "url": "jackson-module-parameter-names-2.15.2.jar",
          "size": 9475,
          "sha512": "89b066c1d10ef9703d943c9f2d388478b59d089cd0134d06523b0be194fae8f557add7dbb4f7e16296f64b27f3b6d2f2fa498087bfb4d8bb45dace433d35930e",
          "sha256": "ebf445ed0897a0e061ee91a43e9e1599a8aaf2f4b79786001bdf4edd256289f4",
          "sha1": "c28f41ceca6cb390eaa492db6d01ec3eb3453af1",
          "md5": "9293dcded6363780aaf339632ebba6b5"
        }
      ]
    }
  ]
}
