{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "3.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.11"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.1.4.jar",
          "url": "spring-boot-starter-logging-3.1.4.jar",
          "size": 4760,
          "sha512": "2c57614e1326824c51719821b46bb5ec758dffea9255d10cb5af24e138e3fa74b16e14cf5d354dda1fe80ff82e2324946077e3b553d0ca4770414f9759b09f47",
          "sha256": "95e852ef48bc18f9c0561b56808183d8b4a24af5744404aca9364b5f2ac517bc",
          "sha1": "e3533d7b6e2e9b5ca9b05dce2a9a2504aad5b889",
          "md5": "cd05f824b68bab972f044a995edbfb17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.11"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.20.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.1.4.jar",
          "url": "spring-boot-starter-logging-3.1.4.jar",
          "size": 4760,
          "sha512": "2c57614e1326824c51719821b46bb5ec758dffea9255d10cb5af24e138e3fa74b16e14cf5d354dda1fe80ff82e2324946077e3b553d0ca4770414f9759b09f47",
          "sha256": "95e852ef48bc18f9c0561b56808183d8b4a24af5744404aca9364b5f2ac517bc",
          "sha1": "e3533d7b6e2e9b5ca9b05dce2a9a2504aad5b889",
          "md5": "cd05f824b68bab972f044a995edbfb17"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.1.4.jar",
          "url": "spring-boot-starter-logging-3.1.4.jar",
          "size": 4760,
          "sha512": "2c57614e1326824c51719821b46bb5ec758dffea9255d10cb5af24e138e3fa74b16e14cf5d354dda1fe80ff82e2324946077e3b553d0ca4770414f9759b09f47",
          "sha256": "95e852ef48bc18f9c0561b56808183d8b4a24af5744404aca9364b5f2ac517bc",
          "sha1": "e3533d7b6e2e9b5ca9b05dce2a9a2504aad5b889",
          "md5": "cd05f824b68bab972f044a995edbfb17"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-logging-maven-optional",
          "version": "3.1.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.1.4.jar",
          "url": "spring-boot-starter-logging-3.1.4.jar",
          "size": 4760,
          "sha512": "2c57614e1326824c51719821b46bb5ec758dffea9255d10cb5af24e138e3fa74b16e14cf5d354dda1fe80ff82e2324946077e3b553d0ca4770414f9759b09f47",
          "sha256": "95e852ef48bc18f9c0561b56808183d8b4a24af5744404aca9364b5f2ac517bc",
          "sha1": "e3533d7b6e2e9b5ca9b05dce2a9a2504aad5b889",
          "md5": "cd05f824b68bab972f044a995edbfb17"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-logging-maven-optional",
          "version": "3.1.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.1.4-javadoc.jar",
          "url": "spring-boot-starter-logging-3.1.4-javadoc.jar",
          "size": 4743,
          "sha512": "5990df6ed6c63a82449036596ac9aaba67009fc31216d25206d77e89bcd81ffda7aec6e1edcc378cb8af2cb1451e7940facf1e13a240caf54159a4f3e18f2e00",
          "sha256": "8d2e63569d265af72f23c17ef70b09d92c666da9d0a484b10313ed3d34b9494f",
          "sha1": "4a1d72199ff8c516b4a6baa778589ce05390e68f",
          "md5": "c87979861c15b8ddd41fa9d5389feaa9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.1.4-sources.jar",
          "url": "spring-boot-starter-logging-3.1.4-sources.jar",
          "size": 4742,
          "sha512": "4daee4c0b9113b9544adf540d573761a6e39be89bb7b73d52a602ca64bde6d8c44e370b55825c90b381f84905a0e61e37529067305090c90671fd3b6153e7b18",
          "sha256": "afc89fd19b30f55ece3088011e57f49e97db3323371c0a8c0d71203bc67f8b71",
          "sha1": "773c2ff801a37012a199c5cbf2a3dc99d654606a",
          "md5": "a0a08112b347b1e8955ad596c561f4e3"
        }
      ]
    }
  ]
}
