{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "3.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.1.4.jar",
          "url": "spring-boot-starter-3.1.4.jar",
          "size": 4768,
          "sha512": "c92e3ae419908cca498c6b09139e5c0602d06ccb4018c276195d6135212214f4e17f02a007fb99ad682aacb94bdcd00b7d1dc0dbe19f73658ced4c81fc9973bf",
          "sha256": "08266034df7c3ea63b961def06454571d4c3844ee22dab34ef5e292c9354f00d",
          "sha1": "8a615e53a9f45eecc4821917b1423daa68afcf19",
          "md5": "5e34ae4dd67f995b245aabc1c5437f57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.12"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.1.4.jar",
          "url": "spring-boot-starter-3.1.4.jar",
          "size": 4768,
          "sha512": "c92e3ae419908cca498c6b09139e5c0602d06ccb4018c276195d6135212214f4e17f02a007fb99ad682aacb94bdcd00b7d1dc0dbe19f73658ced4c81fc9973bf",
          "sha256": "08266034df7c3ea63b961def06454571d4c3844ee22dab34ef5e292c9354f00d",
          "sha1": "8a615e53a9f45eecc4821917b1423daa68afcf19",
          "md5": "5e34ae4dd67f995b245aabc1c5437f57"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.1.4.jar",
          "url": "spring-boot-starter-3.1.4.jar",
          "size": 4768,
          "sha512": "c92e3ae419908cca498c6b09139e5c0602d06ccb4018c276195d6135212214f4e17f02a007fb99ad682aacb94bdcd00b7d1dc0dbe19f73658ced4c81fc9973bf",
          "sha256": "08266034df7c3ea63b961def06454571d4c3844ee22dab34ef5e292c9354f00d",
          "sha1": "8a615e53a9f45eecc4821917b1423daa68afcf19",
          "md5": "5e34ae4dd67f995b245aabc1c5437f57"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.1.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.1.4.jar",
          "url": "spring-boot-starter-3.1.4.jar",
          "size": 4768,
          "sha512": "c92e3ae419908cca498c6b09139e5c0602d06ccb4018c276195d6135212214f4e17f02a007fb99ad682aacb94bdcd00b7d1dc0dbe19f73658ced4c81fc9973bf",
          "sha256": "08266034df7c3ea63b961def06454571d4c3844ee22dab34ef5e292c9354f00d",
          "sha1": "8a615e53a9f45eecc4821917b1423daa68afcf19",
          "md5": "5e34ae4dd67f995b245aabc1c5437f57"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.1.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.1.4-javadoc.jar",
          "url": "spring-boot-starter-3.1.4-javadoc.jar",
          "size": 4734,
          "sha512": "2a19f3e147a7bd1ad1bb66150e73ed8848f6df3c832cf09cf054b59d97a3f029d210605aad09eb0108fa81a526d676c7702d375003f85a98d5f72b4ea849b773",
          "sha256": "1421737ea5d18ee931d5100dd62575ae758eba78d2ae079b8c73095ec0847cd6",
          "sha1": "c720008133110ed3475517c56e8b3caad40de495",
          "md5": "31ef45d036d1f85fe9847e1ff7a65b12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.1.4-sources.jar",
          "url": "spring-boot-starter-3.1.4-sources.jar",
          "size": 4734,
          "sha512": "c3b5838879ccbe36b2c1f5b204c498cfe0349db66dae849401b77069bf1c95a6984a89a5acebbb4a6ec62b88a9fff3007d31f68e3d005e8c6c92d35e9d0f379d",
          "sha256": "33e2bd5315723ce66963e3a17282c78e8c226a5da6692fba85bb4e4545e9963a",
          "sha1": "1bd4f884153460a033de2c264e755ec33709e7cb",
          "md5": "68e3e360adff982713acfeaefb183934"
        }
      ]
    }
  ]
}
